#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pkurg.PWorldBPM.Services.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BPM")]
	public partial class Linq2BPMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertWF_AppDict(WF_AppDict instance);
    partial void UpdateWF_AppDict(WF_AppDict instance);
    partial void DeleteWF_AppDict(WF_AppDict instance);
    partial void InsertWF_WorkFlowInstance(WF_WorkFlowInstance instance);
    partial void UpdateWF_WorkFlowInstance(WF_WorkFlowInstance instance);
    partial void DeleteWF_WorkFlowInstance(WF_WorkFlowInstance instance);
    partial void InsertBPM_Attachment(BPM_Attachment instance);
    partial void UpdateBPM_Attachment(BPM_Attachment instance);
    partial void DeleteBPM_Attachment(BPM_Attachment instance);
    partial void InsertArchive_Log(Archive_Log instance);
    partial void UpdateArchive_Log(Archive_Log instance);
    partial void DeleteArchive_Log(Archive_Log instance);
    #endregion
		
		public Linq2BPMDataContext() : 
				base(global::Pkurg.PWorldBPM.Services.DAL.Properties.Settings.Default.BPMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Linq2BPMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Linq2BPMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Linq2BPMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Linq2BPMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<WF_AppDict> WF_AppDict
		{
			get
			{
				return this.GetTable<WF_AppDict>();
			}
		}
		
		public System.Data.Linq.Table<WF_WorkFlowInstance> WF_WorkFlowInstance
		{
			get
			{
				return this.GetTable<WF_WorkFlowInstance>();
			}
		}
		
		public System.Data.Linq.Table<BPM_Attachment> BPM_Attachment
		{
			get
			{
				return this.GetTable<BPM_Attachment>();
			}
		}
		
		public System.Data.Linq.Table<V_BPM_Archive> V_BPM_Archive
		{
			get
			{
				return this.GetTable<V_BPM_Archive>();
			}
		}
		
		public System.Data.Linq.Table<Archive_Log> Archive_Log
		{
			get
			{
				return this.GetTable<Archive_Log>();
			}
		}
		
		public System.Data.Linq.Table<V_Pworld_UserInfo_All> V_Pworld_UserInfo_All
		{
			get
			{
				return this.GetTable<V_Pworld_UserInfo_All>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WF_AppDict")]
	public partial class WF_AppDict : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _AppId;
		
		private string _AppName;
		
		private System.Nullable<int> _AppType;
		
		private string _WorkFlowName;
		
		private string _FormName;
		
		private System.Nullable<int> _IsOpen;
		
		private System.Nullable<int> _IsNeedArchive;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAppIdChanging(string value);
    partial void OnAppIdChanged();
    partial void OnAppNameChanging(string value);
    partial void OnAppNameChanged();
    partial void OnAppTypeChanging(System.Nullable<int> value);
    partial void OnAppTypeChanged();
    partial void OnWorkFlowNameChanging(string value);
    partial void OnWorkFlowNameChanged();
    partial void OnFormNameChanging(string value);
    partial void OnFormNameChanged();
    partial void OnIsOpenChanging(System.Nullable<int> value);
    partial void OnIsOpenChanged();
    partial void OnIsNeedArchiveChanging(System.Nullable<int> value);
    partial void OnIsNeedArchiveChanged();
    #endregion
		
		public WF_AppDict()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppId", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string AppId
		{
			get
			{
				return this._AppId;
			}
			set
			{
				if ((this._AppId != value))
				{
					this.OnAppIdChanging(value);
					this.SendPropertyChanging();
					this._AppId = value;
					this.SendPropertyChanged("AppId");
					this.OnAppIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppName", DbType="VarChar(500)")]
		public string AppName
		{
			get
			{
				return this._AppName;
			}
			set
			{
				if ((this._AppName != value))
				{
					this.OnAppNameChanging(value);
					this.SendPropertyChanging();
					this._AppName = value;
					this.SendPropertyChanged("AppName");
					this.OnAppNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppType", DbType="Int")]
		public System.Nullable<int> AppType
		{
			get
			{
				return this._AppType;
			}
			set
			{
				if ((this._AppType != value))
				{
					this.OnAppTypeChanging(value);
					this.SendPropertyChanging();
					this._AppType = value;
					this.SendPropertyChanged("AppType");
					this.OnAppTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkFlowName", DbType="VarChar(500)")]
		public string WorkFlowName
		{
			get
			{
				return this._WorkFlowName;
			}
			set
			{
				if ((this._WorkFlowName != value))
				{
					this.OnWorkFlowNameChanging(value);
					this.SendPropertyChanging();
					this._WorkFlowName = value;
					this.SendPropertyChanged("WorkFlowName");
					this.OnWorkFlowNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormName", DbType="VarChar(1000)")]
		public string FormName
		{
			get
			{
				return this._FormName;
			}
			set
			{
				if ((this._FormName != value))
				{
					this.OnFormNameChanging(value);
					this.SendPropertyChanging();
					this._FormName = value;
					this.SendPropertyChanged("FormName");
					this.OnFormNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsOpen", DbType="Int")]
		public System.Nullable<int> IsOpen
		{
			get
			{
				return this._IsOpen;
			}
			set
			{
				if ((this._IsOpen != value))
				{
					this.OnIsOpenChanging(value);
					this.SendPropertyChanging();
					this._IsOpen = value;
					this.SendPropertyChanged("IsOpen");
					this.OnIsOpenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsNeedArchive", DbType="Int")]
		public System.Nullable<int> IsNeedArchive
		{
			get
			{
				return this._IsNeedArchive;
			}
			set
			{
				if ((this._IsNeedArchive != value))
				{
					this.OnIsNeedArchiveChanging(value);
					this.SendPropertyChanging();
					this._IsNeedArchive = value;
					this.SendPropertyChanged("IsNeedArchive");
					this.OnIsNeedArchiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WF_WorkFlowInstance")]
	public partial class WF_WorkFlowInstance : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _InstanceID;
		
		private string _AppID;
		
		private string _FormID;
		
		private string _WFInstanceId;
		
		private System.Nullable<int> _OrderNo;
		
		private System.Nullable<int> _IsDel;
		
		private string _CreateByUserCode;
		
		private string _CreateByUserName;
		
		private System.Nullable<System.DateTime> _CreateAtTime;
		
		private string _UpdateByUserCode;
		
		private string _UpdateByUserName;
		
		private System.Nullable<System.DateTime> _UpdateAtTime;
		
		private string _CreateDeptCode;
		
		private string _CreateDeptName;
		
		private string _WorkItemCode;
		
		private string _WorkItemName;
		
		private System.Nullable<int> _WFTaskID;
		
		private System.Nullable<System.DateTime> _FinishedTime;
		
		private string _Remark;
		
		private string _FormTitle;
		
		private string _WFStatus;
		
		private System.Nullable<System.DateTime> _SumitTime;
		
		private System.Xml.Linq.XElement _FormData;
		
		private string _ProcessName;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnInstanceIDChanging(string value);
    partial void OnInstanceIDChanged();
    partial void OnAppIDChanging(string value);
    partial void OnAppIDChanged();
    partial void OnFormIDChanging(string value);
    partial void OnFormIDChanged();
    partial void OnWFInstanceIdChanging(string value);
    partial void OnWFInstanceIdChanged();
    partial void OnOrderNoChanging(System.Nullable<int> value);
    partial void OnOrderNoChanged();
    partial void OnIsDelChanging(System.Nullable<int> value);
    partial void OnIsDelChanged();
    partial void OnCreateByUserCodeChanging(string value);
    partial void OnCreateByUserCodeChanged();
    partial void OnCreateByUserNameChanging(string value);
    partial void OnCreateByUserNameChanged();
    partial void OnCreateAtTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateAtTimeChanged();
    partial void OnUpdateByUserCodeChanging(string value);
    partial void OnUpdateByUserCodeChanged();
    partial void OnUpdateByUserNameChanging(string value);
    partial void OnUpdateByUserNameChanged();
    partial void OnUpdateAtTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateAtTimeChanged();
    partial void OnCreateDeptCodeChanging(string value);
    partial void OnCreateDeptCodeChanged();
    partial void OnCreateDeptNameChanging(string value);
    partial void OnCreateDeptNameChanged();
    partial void OnWorkItemCodeChanging(string value);
    partial void OnWorkItemCodeChanged();
    partial void OnWorkItemNameChanging(string value);
    partial void OnWorkItemNameChanged();
    partial void OnWFTaskIDChanging(System.Nullable<int> value);
    partial void OnWFTaskIDChanged();
    partial void OnFinishedTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnFinishedTimeChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnFormTitleChanging(string value);
    partial void OnFormTitleChanged();
    partial void OnWFStatusChanging(string value);
    partial void OnWFStatusChanged();
    partial void OnSumitTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnSumitTimeChanged();
    partial void OnFormDataChanging(System.Xml.Linq.XElement value);
    partial void OnFormDataChanged();
    partial void OnProcessNameChanging(string value);
    partial void OnProcessNameChanged();
    #endregion
		
		public WF_WorkFlowInstance()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstanceID", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string InstanceID
		{
			get
			{
				return this._InstanceID;
			}
			set
			{
				if ((this._InstanceID != value))
				{
					this.OnInstanceIDChanging(value);
					this.SendPropertyChanging();
					this._InstanceID = value;
					this.SendPropertyChanged("InstanceID");
					this.OnInstanceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppID", DbType="NVarChar(100)")]
		public string AppID
		{
			get
			{
				return this._AppID;
			}
			set
			{
				if ((this._AppID != value))
				{
					this.OnAppIDChanging(value);
					this.SendPropertyChanging();
					this._AppID = value;
					this.SendPropertyChanged("AppID");
					this.OnAppIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormID", DbType="NVarChar(200)")]
		public string FormID
		{
			get
			{
				return this._FormID;
			}
			set
			{
				if ((this._FormID != value))
				{
					this.OnFormIDChanging(value);
					this.SendPropertyChanging();
					this._FormID = value;
					this.SendPropertyChanged("FormID");
					this.OnFormIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WFInstanceId", DbType="NVarChar(100)")]
		public string WFInstanceId
		{
			get
			{
				return this._WFInstanceId;
			}
			set
			{
				if ((this._WFInstanceId != value))
				{
					this.OnWFInstanceIdChanging(value);
					this.SendPropertyChanging();
					this._WFInstanceId = value;
					this.SendPropertyChanged("WFInstanceId");
					this.OnWFInstanceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNo", DbType="Int")]
		public System.Nullable<int> OrderNo
		{
			get
			{
				return this._OrderNo;
			}
			set
			{
				if ((this._OrderNo != value))
				{
					this.OnOrderNoChanging(value);
					this.SendPropertyChanging();
					this._OrderNo = value;
					this.SendPropertyChanged("OrderNo");
					this.OnOrderNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDel", DbType="Int")]
		public System.Nullable<int> IsDel
		{
			get
			{
				return this._IsDel;
			}
			set
			{
				if ((this._IsDel != value))
				{
					this.OnIsDelChanging(value);
					this.SendPropertyChanging();
					this._IsDel = value;
					this.SendPropertyChanged("IsDel");
					this.OnIsDelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateByUserCode", DbType="NVarChar(50)")]
		public string CreateByUserCode
		{
			get
			{
				return this._CreateByUserCode;
			}
			set
			{
				if ((this._CreateByUserCode != value))
				{
					this.OnCreateByUserCodeChanging(value);
					this.SendPropertyChanging();
					this._CreateByUserCode = value;
					this.SendPropertyChanged("CreateByUserCode");
					this.OnCreateByUserCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateByUserName", DbType="NVarChar(50)")]
		public string CreateByUserName
		{
			get
			{
				return this._CreateByUserName;
			}
			set
			{
				if ((this._CreateByUserName != value))
				{
					this.OnCreateByUserNameChanging(value);
					this.SendPropertyChanging();
					this._CreateByUserName = value;
					this.SendPropertyChanged("CreateByUserName");
					this.OnCreateByUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateAtTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateAtTime
		{
			get
			{
				return this._CreateAtTime;
			}
			set
			{
				if ((this._CreateAtTime != value))
				{
					this.OnCreateAtTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateAtTime = value;
					this.SendPropertyChanged("CreateAtTime");
					this.OnCreateAtTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateByUserCode", DbType="NVarChar(50)")]
		public string UpdateByUserCode
		{
			get
			{
				return this._UpdateByUserCode;
			}
			set
			{
				if ((this._UpdateByUserCode != value))
				{
					this.OnUpdateByUserCodeChanging(value);
					this.SendPropertyChanging();
					this._UpdateByUserCode = value;
					this.SendPropertyChanged("UpdateByUserCode");
					this.OnUpdateByUserCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateByUserName", DbType="NVarChar(50)")]
		public string UpdateByUserName
		{
			get
			{
				return this._UpdateByUserName;
			}
			set
			{
				if ((this._UpdateByUserName != value))
				{
					this.OnUpdateByUserNameChanging(value);
					this.SendPropertyChanging();
					this._UpdateByUserName = value;
					this.SendPropertyChanged("UpdateByUserName");
					this.OnUpdateByUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateAtTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateAtTime
		{
			get
			{
				return this._UpdateAtTime;
			}
			set
			{
				if ((this._UpdateAtTime != value))
				{
					this.OnUpdateAtTimeChanging(value);
					this.SendPropertyChanging();
					this._UpdateAtTime = value;
					this.SendPropertyChanged("UpdateAtTime");
					this.OnUpdateAtTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDeptCode", DbType="NVarChar(50)")]
		public string CreateDeptCode
		{
			get
			{
				return this._CreateDeptCode;
			}
			set
			{
				if ((this._CreateDeptCode != value))
				{
					this.OnCreateDeptCodeChanging(value);
					this.SendPropertyChanging();
					this._CreateDeptCode = value;
					this.SendPropertyChanged("CreateDeptCode");
					this.OnCreateDeptCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDeptName", DbType="NVarChar(50)")]
		public string CreateDeptName
		{
			get
			{
				return this._CreateDeptName;
			}
			set
			{
				if ((this._CreateDeptName != value))
				{
					this.OnCreateDeptNameChanging(value);
					this.SendPropertyChanging();
					this._CreateDeptName = value;
					this.SendPropertyChanged("CreateDeptName");
					this.OnCreateDeptNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkItemCode", DbType="NVarChar(100)")]
		public string WorkItemCode
		{
			get
			{
				return this._WorkItemCode;
			}
			set
			{
				if ((this._WorkItemCode != value))
				{
					this.OnWorkItemCodeChanging(value);
					this.SendPropertyChanging();
					this._WorkItemCode = value;
					this.SendPropertyChanged("WorkItemCode");
					this.OnWorkItemCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkItemName", DbType="NVarChar(200)")]
		public string WorkItemName
		{
			get
			{
				return this._WorkItemName;
			}
			set
			{
				if ((this._WorkItemName != value))
				{
					this.OnWorkItemNameChanging(value);
					this.SendPropertyChanging();
					this._WorkItemName = value;
					this.SendPropertyChanged("WorkItemName");
					this.OnWorkItemNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WFTaskID", DbType="Int")]
		public System.Nullable<int> WFTaskID
		{
			get
			{
				return this._WFTaskID;
			}
			set
			{
				if ((this._WFTaskID != value))
				{
					this.OnWFTaskIDChanging(value);
					this.SendPropertyChanging();
					this._WFTaskID = value;
					this.SendPropertyChanged("WFTaskID");
					this.OnWFTaskIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinishedTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> FinishedTime
		{
			get
			{
				return this._FinishedTime;
			}
			set
			{
				if ((this._FinishedTime != value))
				{
					this.OnFinishedTimeChanging(value);
					this.SendPropertyChanging();
					this._FinishedTime = value;
					this.SendPropertyChanged("FinishedTime");
					this.OnFinishedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(500)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormTitle", DbType="NVarChar(300)")]
		public string FormTitle
		{
			get
			{
				return this._FormTitle;
			}
			set
			{
				if ((this._FormTitle != value))
				{
					this.OnFormTitleChanging(value);
					this.SendPropertyChanging();
					this._FormTitle = value;
					this.SendPropertyChanged("FormTitle");
					this.OnFormTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WFStatus", DbType="NVarChar(10)")]
		public string WFStatus
		{
			get
			{
				return this._WFStatus;
			}
			set
			{
				if ((this._WFStatus != value))
				{
					this.OnWFStatusChanging(value);
					this.SendPropertyChanging();
					this._WFStatus = value;
					this.SendPropertyChanged("WFStatus");
					this.OnWFStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SumitTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> SumitTime
		{
			get
			{
				return this._SumitTime;
			}
			set
			{
				if ((this._SumitTime != value))
				{
					this.OnSumitTimeChanging(value);
					this.SendPropertyChanging();
					this._SumitTime = value;
					this.SendPropertyChanged("SumitTime");
					this.OnSumitTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormData", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement FormData
		{
			get
			{
				return this._FormData;
			}
			set
			{
				if ((this._FormData != value))
				{
					this.OnFormDataChanging(value);
					this.SendPropertyChanging();
					this._FormData = value;
					this.SendPropertyChanged("FormData");
					this.OnFormDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessName", DbType="NVarChar(200)")]
		public string ProcessName
		{
			get
			{
				return this._ProcessName;
			}
			set
			{
				if ((this._ProcessName != value))
				{
					this.OnProcessNameChanging(value);
					this.SendPropertyChanging();
					this._ProcessName = value;
					this.SendPropertyChanged("ProcessName");
					this.OnProcessNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BPM_Attachment")]
	public partial class BPM_Attachment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _AttachmentID;
		
		private string _FormID;
		
		private string _AttachmentName;
		
		private System.Nullable<int> _OrderNo;
		
		private System.Nullable<int> _IsDel;
		
		private string _CreateByUserCode;
		
		private string _CreateByUserName;
		
		private System.Nullable<System.DateTime> _CreateAtTime;
		
		private string _UpdateByUserCode;
		
		private string _UpdateByUserName;
		
		private System.Nullable<System.DateTime> _UpdateAtTime;
		
		private string _URL;
		
		private string _AttachmentSize;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAttachmentIDChanging(string value);
    partial void OnAttachmentIDChanged();
    partial void OnFormIDChanging(string value);
    partial void OnFormIDChanged();
    partial void OnAttachmentNameChanging(string value);
    partial void OnAttachmentNameChanged();
    partial void OnOrderNoChanging(System.Nullable<int> value);
    partial void OnOrderNoChanged();
    partial void OnIsDelChanging(System.Nullable<int> value);
    partial void OnIsDelChanged();
    partial void OnCreateByUserCodeChanging(string value);
    partial void OnCreateByUserCodeChanged();
    partial void OnCreateByUserNameChanging(string value);
    partial void OnCreateByUserNameChanged();
    partial void OnCreateAtTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateAtTimeChanged();
    partial void OnUpdateByUserCodeChanging(string value);
    partial void OnUpdateByUserCodeChanged();
    partial void OnUpdateByUserNameChanging(string value);
    partial void OnUpdateByUserNameChanged();
    partial void OnUpdateAtTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateAtTimeChanged();
    partial void OnURLChanging(string value);
    partial void OnURLChanged();
    partial void OnAttachmentSizeChanging(string value);
    partial void OnAttachmentSizeChanged();
    #endregion
		
		public BPM_Attachment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttachmentID", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string AttachmentID
		{
			get
			{
				return this._AttachmentID;
			}
			set
			{
				if ((this._AttachmentID != value))
				{
					this.OnAttachmentIDChanging(value);
					this.SendPropertyChanging();
					this._AttachmentID = value;
					this.SendPropertyChanged("AttachmentID");
					this.OnAttachmentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormID", DbType="NVarChar(200)")]
		public string FormID
		{
			get
			{
				return this._FormID;
			}
			set
			{
				if ((this._FormID != value))
				{
					this.OnFormIDChanging(value);
					this.SendPropertyChanging();
					this._FormID = value;
					this.SendPropertyChanged("FormID");
					this.OnFormIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttachmentName", DbType="NVarChar(200)")]
		public string AttachmentName
		{
			get
			{
				return this._AttachmentName;
			}
			set
			{
				if ((this._AttachmentName != value))
				{
					this.OnAttachmentNameChanging(value);
					this.SendPropertyChanging();
					this._AttachmentName = value;
					this.SendPropertyChanged("AttachmentName");
					this.OnAttachmentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNo", DbType="Int")]
		public System.Nullable<int> OrderNo
		{
			get
			{
				return this._OrderNo;
			}
			set
			{
				if ((this._OrderNo != value))
				{
					this.OnOrderNoChanging(value);
					this.SendPropertyChanging();
					this._OrderNo = value;
					this.SendPropertyChanged("OrderNo");
					this.OnOrderNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDel", DbType="Int")]
		public System.Nullable<int> IsDel
		{
			get
			{
				return this._IsDel;
			}
			set
			{
				if ((this._IsDel != value))
				{
					this.OnIsDelChanging(value);
					this.SendPropertyChanging();
					this._IsDel = value;
					this.SendPropertyChanged("IsDel");
					this.OnIsDelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateByUserCode", DbType="NVarChar(100)")]
		public string CreateByUserCode
		{
			get
			{
				return this._CreateByUserCode;
			}
			set
			{
				if ((this._CreateByUserCode != value))
				{
					this.OnCreateByUserCodeChanging(value);
					this.SendPropertyChanging();
					this._CreateByUserCode = value;
					this.SendPropertyChanged("CreateByUserCode");
					this.OnCreateByUserCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateByUserName", DbType="NVarChar(100)")]
		public string CreateByUserName
		{
			get
			{
				return this._CreateByUserName;
			}
			set
			{
				if ((this._CreateByUserName != value))
				{
					this.OnCreateByUserNameChanging(value);
					this.SendPropertyChanging();
					this._CreateByUserName = value;
					this.SendPropertyChanged("CreateByUserName");
					this.OnCreateByUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateAtTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateAtTime
		{
			get
			{
				return this._CreateAtTime;
			}
			set
			{
				if ((this._CreateAtTime != value))
				{
					this.OnCreateAtTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateAtTime = value;
					this.SendPropertyChanged("CreateAtTime");
					this.OnCreateAtTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateByUserCode", DbType="NVarChar(100)")]
		public string UpdateByUserCode
		{
			get
			{
				return this._UpdateByUserCode;
			}
			set
			{
				if ((this._UpdateByUserCode != value))
				{
					this.OnUpdateByUserCodeChanging(value);
					this.SendPropertyChanging();
					this._UpdateByUserCode = value;
					this.SendPropertyChanged("UpdateByUserCode");
					this.OnUpdateByUserCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateByUserName", DbType="NVarChar(100)")]
		public string UpdateByUserName
		{
			get
			{
				return this._UpdateByUserName;
			}
			set
			{
				if ((this._UpdateByUserName != value))
				{
					this.OnUpdateByUserNameChanging(value);
					this.SendPropertyChanging();
					this._UpdateByUserName = value;
					this.SendPropertyChanged("UpdateByUserName");
					this.OnUpdateByUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateAtTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateAtTime
		{
			get
			{
				return this._UpdateAtTime;
			}
			set
			{
				if ((this._UpdateAtTime != value))
				{
					this.OnUpdateAtTimeChanging(value);
					this.SendPropertyChanging();
					this._UpdateAtTime = value;
					this.SendPropertyChanged("UpdateAtTime");
					this.OnUpdateAtTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="NVarChar(500)")]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this.OnURLChanging(value);
					this.SendPropertyChanging();
					this._URL = value;
					this.SendPropertyChanged("URL");
					this.OnURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttachmentSize", DbType="NVarChar(100)")]
		public string AttachmentSize
		{
			get
			{
				return this._AttachmentSize;
			}
			set
			{
				if ((this._AttachmentSize != value))
				{
					this.OnAttachmentSizeChanging(value);
					this.SendPropertyChanging();
					this._AttachmentSize = value;
					this.SendPropertyChanged("AttachmentSize");
					this.OnAttachmentSizeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_BPM_Archive")]
	public partial class V_BPM_Archive
	{
		
		private string _InstanceID;
		
		private string _AppID;
		
		private string _FormName;
		
		private string _FormID;
		
		private string _WFInstanceId;
		
		private System.Nullable<int> _OrderNo;
		
		private System.Nullable<int> _IsDel;
		
		private string _CreateByUserCode;
		
		private string _CreateByUserName;
		
		private System.Nullable<System.DateTime> _CreateAtTime;
		
		private string _UpdateByUserCode;
		
		private string _UpdateByUserName;
		
		private System.Nullable<System.DateTime> _UpdateAtTime;
		
		private string _CreateDeptCode;
		
		private string _CreateDeptName;
		
		private string _WorkItemCode;
		
		private string _WorkItemName;
		
		private System.Nullable<int> _WFTaskID;
		
		private System.Nullable<System.DateTime> _FinishedTime;
		
		private string _Remark;
		
		private string _FormTitle;
		
		private string _WFStatus;
		
		private System.Nullable<System.DateTime> _SumitTime;
		
		private System.Xml.Linq.XElement _FormData;
		
		private string _ProcessName;
		
		public V_BPM_Archive()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstanceID", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string InstanceID
		{
			get
			{
				return this._InstanceID;
			}
			set
			{
				if ((this._InstanceID != value))
				{
					this._InstanceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppID", DbType="NVarChar(100)")]
		public string AppID
		{
			get
			{
				return this._AppID;
			}
			set
			{
				if ((this._AppID != value))
				{
					this._AppID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormName", DbType="VarChar(1000)")]
		public string FormName
		{
			get
			{
				return this._FormName;
			}
			set
			{
				if ((this._FormName != value))
				{
					this._FormName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormID", DbType="NVarChar(200)")]
		public string FormID
		{
			get
			{
				return this._FormID;
			}
			set
			{
				if ((this._FormID != value))
				{
					this._FormID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WFInstanceId", DbType="NVarChar(100)")]
		public string WFInstanceId
		{
			get
			{
				return this._WFInstanceId;
			}
			set
			{
				if ((this._WFInstanceId != value))
				{
					this._WFInstanceId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNo", DbType="Int")]
		public System.Nullable<int> OrderNo
		{
			get
			{
				return this._OrderNo;
			}
			set
			{
				if ((this._OrderNo != value))
				{
					this._OrderNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDel", DbType="Int")]
		public System.Nullable<int> IsDel
		{
			get
			{
				return this._IsDel;
			}
			set
			{
				if ((this._IsDel != value))
				{
					this._IsDel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateByUserCode", DbType="NVarChar(50)")]
		public string CreateByUserCode
		{
			get
			{
				return this._CreateByUserCode;
			}
			set
			{
				if ((this._CreateByUserCode != value))
				{
					this._CreateByUserCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateByUserName", DbType="NVarChar(50)")]
		public string CreateByUserName
		{
			get
			{
				return this._CreateByUserName;
			}
			set
			{
				if ((this._CreateByUserName != value))
				{
					this._CreateByUserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateAtTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateAtTime
		{
			get
			{
				return this._CreateAtTime;
			}
			set
			{
				if ((this._CreateAtTime != value))
				{
					this._CreateAtTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateByUserCode", DbType="NVarChar(50)")]
		public string UpdateByUserCode
		{
			get
			{
				return this._UpdateByUserCode;
			}
			set
			{
				if ((this._UpdateByUserCode != value))
				{
					this._UpdateByUserCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateByUserName", DbType="NVarChar(50)")]
		public string UpdateByUserName
		{
			get
			{
				return this._UpdateByUserName;
			}
			set
			{
				if ((this._UpdateByUserName != value))
				{
					this._UpdateByUserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateAtTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateAtTime
		{
			get
			{
				return this._UpdateAtTime;
			}
			set
			{
				if ((this._UpdateAtTime != value))
				{
					this._UpdateAtTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDeptCode", DbType="NVarChar(50)")]
		public string CreateDeptCode
		{
			get
			{
				return this._CreateDeptCode;
			}
			set
			{
				if ((this._CreateDeptCode != value))
				{
					this._CreateDeptCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDeptName", DbType="NVarChar(50)")]
		public string CreateDeptName
		{
			get
			{
				return this._CreateDeptName;
			}
			set
			{
				if ((this._CreateDeptName != value))
				{
					this._CreateDeptName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkItemCode", DbType="NVarChar(100)")]
		public string WorkItemCode
		{
			get
			{
				return this._WorkItemCode;
			}
			set
			{
				if ((this._WorkItemCode != value))
				{
					this._WorkItemCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkItemName", DbType="NVarChar(200)")]
		public string WorkItemName
		{
			get
			{
				return this._WorkItemName;
			}
			set
			{
				if ((this._WorkItemName != value))
				{
					this._WorkItemName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WFTaskID", DbType="Int")]
		public System.Nullable<int> WFTaskID
		{
			get
			{
				return this._WFTaskID;
			}
			set
			{
				if ((this._WFTaskID != value))
				{
					this._WFTaskID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinishedTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> FinishedTime
		{
			get
			{
				return this._FinishedTime;
			}
			set
			{
				if ((this._FinishedTime != value))
				{
					this._FinishedTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(500)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this._Remark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormTitle", DbType="NVarChar(300)")]
		public string FormTitle
		{
			get
			{
				return this._FormTitle;
			}
			set
			{
				if ((this._FormTitle != value))
				{
					this._FormTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WFStatus", DbType="NVarChar(10)")]
		public string WFStatus
		{
			get
			{
				return this._WFStatus;
			}
			set
			{
				if ((this._WFStatus != value))
				{
					this._WFStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SumitTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> SumitTime
		{
			get
			{
				return this._SumitTime;
			}
			set
			{
				if ((this._SumitTime != value))
				{
					this._SumitTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormData", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement FormData
		{
			get
			{
				return this._FormData;
			}
			set
			{
				if ((this._FormData != value))
				{
					this._FormData = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessName", DbType="NVarChar(200)")]
		public string ProcessName
		{
			get
			{
				return this._ProcessName;
			}
			set
			{
				if ((this._ProcessName != value))
				{
					this._ProcessName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Archive_Log")]
	public partial class Archive_Log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _FormID;
		
		private string _InstanceID;
		
		private System.Nullable<int> _IsSuccess;
		
		private System.Nullable<System.DateTime> _CreateTime;
		
		private System.Nullable<System.DateTime> _UpdateTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFormIDChanging(string value);
    partial void OnFormIDChanged();
    partial void OnInstanceIDChanging(string value);
    partial void OnInstanceIDChanged();
    partial void OnIsSuccessChanging(System.Nullable<int> value);
    partial void OnIsSuccessChanged();
    partial void OnCreateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateTimeChanged();
    partial void OnUpdateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateTimeChanged();
    #endregion
		
		public Archive_Log()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormID", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string FormID
		{
			get
			{
				return this._FormID;
			}
			set
			{
				if ((this._FormID != value))
				{
					this.OnFormIDChanging(value);
					this.SendPropertyChanging();
					this._FormID = value;
					this.SendPropertyChanged("FormID");
					this.OnFormIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstanceID", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string InstanceID
		{
			get
			{
				return this._InstanceID;
			}
			set
			{
				if ((this._InstanceID != value))
				{
					this.OnInstanceIDChanging(value);
					this.SendPropertyChanging();
					this._InstanceID = value;
					this.SendPropertyChanged("InstanceID");
					this.OnInstanceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSuccess", DbType="Int")]
		public System.Nullable<int> IsSuccess
		{
			get
			{
				return this._IsSuccess;
			}
			set
			{
				if ((this._IsSuccess != value))
				{
					this.OnIsSuccessChanging(value);
					this.SendPropertyChanging();
					this._IsSuccess = value;
					this.SendPropertyChanged("IsSuccess");
					this.OnIsSuccessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateTime
		{
			get
			{
				return this._CreateTime;
			}
			set
			{
				if ((this._CreateTime != value))
				{
					this.OnCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateTime = value;
					this.SendPropertyChanged("CreateTime");
					this.OnCreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateTime
		{
			get
			{
				return this._UpdateTime;
			}
			set
			{
				if ((this._UpdateTime != value))
				{
					this.OnUpdateTimeChanging(value);
					this.SendPropertyChanging();
					this._UpdateTime = value;
					this.SendPropertyChanged("UpdateTime");
					this.OnUpdateTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_Pworld_UserInfo_All")]
	public partial class V_Pworld_UserInfo_All
	{
		
		private string _EmployeeCode;
		
		private string _EmployeeName;
		
		private string _LoginName;
		
		private string _CompanyCode;
		
		private string _CompanyName;
		
		private string _DepartCode;
		
		private string _DepartName;
		
		private string _Email;
		
		private System.Nullable<int> _Status;
		
		private int _IsDel;
		
		private string _FullPY;
		
		private int _OrderNo;
		
		public V_Pworld_UserInfo_All()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EmployeeCode
		{
			get
			{
				return this._EmployeeCode;
			}
			set
			{
				if ((this._EmployeeCode != value))
				{
					this._EmployeeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeName", DbType="NVarChar(50)")]
		public string EmployeeName
		{
			get
			{
				return this._EmployeeName;
			}
			set
			{
				if ((this._EmployeeName != value))
				{
					this._EmployeeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginName", DbType="NVarChar(50)")]
		public string LoginName
		{
			get
			{
				return this._LoginName;
			}
			set
			{
				if ((this._LoginName != value))
				{
					this._LoginName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyCode", DbType="NVarChar(100)")]
		public string CompanyCode
		{
			get
			{
				return this._CompanyCode;
			}
			set
			{
				if ((this._CompanyCode != value))
				{
					this._CompanyCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(200)")]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this._CompanyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartCode", DbType="NVarChar(500)")]
		public string DepartCode
		{
			get
			{
				return this._DepartCode;
			}
			set
			{
				if ((this._DepartCode != value))
				{
					this._DepartCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartName", DbType="NVarChar(200)")]
		public string DepartName
		{
			get
			{
				return this._DepartName;
			}
			set
			{
				if ((this._DepartName != value))
				{
					this._DepartName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(200)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDel", DbType="Int NOT NULL")]
		public int IsDel
		{
			get
			{
				return this._IsDel;
			}
			set
			{
				if ((this._IsDel != value))
				{
					this._IsDel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullPY", DbType="VarChar(80)")]
		public string FullPY
		{
			get
			{
				return this._FullPY;
			}
			set
			{
				if ((this._FullPY != value))
				{
					this._FullPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNo", DbType="Int NOT NULL")]
		public int OrderNo
		{
			get
			{
				return this._OrderNo;
			}
			set
			{
				if ((this._OrderNo != value))
				{
					this._OrderNo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
