<?xml version="1.0" encoding="utf-8"?><Database Name="BPM" Class="Linq2BPMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.25.20.47;Initial Catalog=BPM;User ID=sa" SettingsObjectName="Pkurg.PWorldBPM.Services.DAL.Properties.Settings" SettingsPropertyName="BPMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.WF_AppDict" Member="WF_AppDict">
    <Type Name="WF_AppDict">
      <Column Name="AppId" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AppName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="AppType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WorkFlowName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="FormName" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IsOpen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsNeedArchive" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WF_WorkFlowInstance" Member="WF_WorkFlowInstance">
    <Type Name="WF_WorkFlowInstance">
      <Column Name="InstanceID" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AppID" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FormID" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="WFInstanceId" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="OrderNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateByUserCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateByUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateAtTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateByUserCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateByUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateAtTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateDeptCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDeptName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WorkItemCode" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="WorkItemName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="WFTaskID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FinishedTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FormTitle" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="WFStatus" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SumitTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FormData" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ProcessName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BPM_Attachment" Member="BPM_Attachment">
    <Type Name="BPM_Attachment">
      <Column Name="AttachmentID" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FormID" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="AttachmentName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="OrderNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateByUserCode" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreateByUserName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreateAtTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateByUserCode" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UpdateByUserName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UpdateAtTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AttachmentSize" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_BPM_Archive" Member="V_BPM_Archive">
    <Type Name="V_BPM_Archive">
      <Column Name="InstanceID" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AppID" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FormName" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FormID" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="WFInstanceId" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="OrderNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateByUserCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateByUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateAtTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateByUserCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateByUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateAtTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateDeptCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDeptName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WorkItemCode" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="WorkItemName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="WFTaskID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FinishedTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FormTitle" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="WFStatus" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SumitTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FormData" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ProcessName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Archive_Log" Member="Archive_Log">
    <Type Name="Archive_Log">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FormID" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="InstanceID" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="IsSuccess" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_Pworld_UserInfo_All" Member="V_Pworld_UserInfo_All">
    <Type Name="V_Pworld_UserInfo_All">
      <Column Name="EmployeeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoginName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CompanyCode" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DepartCode" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DepartName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullPY" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="OrderNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>