//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 

namespace AppCode.ERP
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "ContractApprovalSoap", Namespace = "http://tempuri.org/")]
    public partial class ContractApproval_Service : CommonService
    {

        public ContractApproval_Service()
        {
            this.Url = System.Configuration.ConfigurationManager.AppSettings["FD_ERP_PO_WS"];
        }


        /// <summary>
        /// 超时查询
        /// </summary>
        /// <param name="erpFormCode"></param>
        /// <returns></returns>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerifyERPWFStatus", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ERP_CallbackResultType VerifyERPWFStatus(string erpFormCode)
        {
            try
            {
                object[] results = this.Invoke("VerifyERPWFStatus", new object[] {
                    erpFormCode});
                return ((ERP_CallbackResultType)(results[0]));
            }
            catch (Exception)
            {
                return ERP_CallbackResultType.ERP服务器异常;
            }

        }


    }
}