//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 

namespace AppCode.ERP
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "ERP_ContractFinalAccountSoap", Namespace = "http://tempuri.org/")]
    public partial class ERP_ContractFinalAccount_Service : CommonService
    {
        /// <remarks/>
        public ERP_ContractFinalAccount_Service()
            : base(10111)
        {
           // this.Url = System.Configuration.ConfigurationManager.AppSettings["FD_ERP_QS_WS"];
        }

    }
}