using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "MailServiceSoap", Namespace = "http://tempuri.org/")]
public partial class MailService : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback SendEndEmailOperationCompleted;

    private System.Threading.SendOrPostCallback SendEndEmailCustomOperationCompleted;

    private System.Threading.SendOrPostCallback SendEmailCustomOperationCompleted;

    /// <remarks/>
    public MailService()
    {
        this.Url = "http://172.25.56.57:6666/MailService.asmx";
    }

    /// <remarks/>
    public event SendEndEmailCompletedEventHandler SendEndEmailCompleted;

    /// <remarks/>
    public event SendEndEmailCustomCompletedEventHandler SendEndEmailCustomCompleted;

    /// <remarks/>
    public event SendEmailCustomCompletedEventHandler SendEmailCustomCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEndEmail", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool SendEndEmail(int k2wfId)
    {
        object[] results = this.Invoke("SendEndEmail", new object[] {
                    k2wfId});
        return ((bool)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginSendEndEmail(int k2wfId, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("SendEndEmail", new object[] {
                    k2wfId}, callback, asyncState);
    }

    /// <remarks/>
    public bool EndSendEndEmail(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }

    /// <remarks/>
    public void SendEndEmailAsync(int k2wfId)
    {
        this.SendEndEmailAsync(k2wfId, null);
    }

    /// <remarks/>
    public void SendEndEmailAsync(int k2wfId, object userState)
    {
        if ((this.SendEndEmailOperationCompleted == null))
        {
            this.SendEndEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEndEmailOperationCompleted);
        }
        this.InvokeAsync("SendEndEmail", new object[] {
                    k2wfId}, this.SendEndEmailOperationCompleted, userState);
    }

    private void OnSendEndEmailOperationCompleted(object arg)
    {
        if ((this.SendEndEmailCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendEndEmailCompleted(this, new SendEndEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEndEmailCustom", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool SendEndEmailCustom(int k2wfId, string title, string body)
    {
        object[] results = this.Invoke("SendEndEmailCustom", new object[] {
                    k2wfId,
                    title,
                    body});
        return ((bool)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginSendEndEmailCustom(int k2wfId, string title, string body, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("SendEndEmailCustom", new object[] {
                    k2wfId,
                    title,
                    body}, callback, asyncState);
    }

    /// <remarks/>
    public bool EndSendEndEmailCustom(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }

    /// <remarks/>
    public void SendEndEmailCustomAsync(int k2wfId, string title, string body)
    {
        this.SendEndEmailCustomAsync(k2wfId, title, body, null);
    }

    /// <remarks/>
    public void SendEndEmailCustomAsync(int k2wfId, string title, string body, object userState)
    {
        if ((this.SendEndEmailCustomOperationCompleted == null))
        {
            this.SendEndEmailCustomOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEndEmailCustomOperationCompleted);
        }
        this.InvokeAsync("SendEndEmailCustom", new object[] {
                    k2wfId,
                    title,
                    body}, this.SendEndEmailCustomOperationCompleted, userState);
    }

    private void OnSendEndEmailCustomOperationCompleted(object arg)
    {
        if ((this.SendEndEmailCustomCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendEndEmailCustomCompleted(this, new SendEndEmailCustomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmailCustom", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool SendEmailCustom(string toUsers, string title, string body)
    {
        object[] results = this.Invoke("SendEmailCustom", new object[] {
                    toUsers,
                    title,
                    body});
        return ((bool)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginSendEmailCustom(string toUsers, string title, string body, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("SendEmailCustom", new object[] {
                    toUsers,
                    title,
                    body}, callback, asyncState);
    }

    /// <remarks/>
    public bool EndSendEmailCustom(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }

    /// <remarks/>
    public void SendEmailCustomAsync(string toUsers, string title, string body)
    {
        this.SendEmailCustomAsync(toUsers, title, body, null);
    }

    /// <remarks/>
    public void SendEmailCustomAsync(string toUsers, string title, string body, object userState)
    {
        if ((this.SendEmailCustomOperationCompleted == null))
        {
            this.SendEmailCustomOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmailCustomOperationCompleted);
        }
        this.InvokeAsync("SendEmailCustom", new object[] {
                    toUsers,
                    title,
                    body}, this.SendEmailCustomOperationCompleted, userState);
    }

    private void OnSendEmailCustomOperationCompleted(object arg)
    {
        if ((this.SendEmailCustomCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendEmailCustomCompleted(this, new SendEmailCustomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void SendEndEmailCompletedEventHandler(object sender, SendEndEmailCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SendEndEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal SendEndEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public bool Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void SendEndEmailCustomCompletedEventHandler(object sender, SendEndEmailCustomCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SendEndEmailCustomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal SendEndEmailCustomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public bool Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void SendEmailCustomCompletedEventHandler(object sender, SendEmailCustomCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SendEmailCustomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal SendEmailCustomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public bool Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}
