//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.296 版自动生成。
// 
#pragma warning disable 1591

namespace Pkurg.PWorldBPM.Services.WinForm.WSArchive {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DbUtilServiceHttpBinding", Namespace="thamsspace")]
    public partial class DbUtilService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback deleteFieldOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBMIDByADUserNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback modifyFieldOperationCompleted;
        
        private System.Threading.SendOrPostCallback addFieldOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DbUtilService() {
            this.Url = global::Pkurg.PWorldBPM.Services.WinForm.Properties.Settings.Default.Pkurg_PWorldBPM_Services_WinForm_WSArchive_DbUtilService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event deleteFieldCompletedEventHandler deleteFieldCompleted;
        
        /// <remarks/>
        public event getBMIDByADUserNameCompletedEventHandler getBMIDByADUserNameCompleted;
        
        /// <remarks/>
        public event modifyFieldCompletedEventHandler modifyFieldCompleted;
        
        /// <remarks/>
        public event addFieldCompletedEventHandler addFieldCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="thamsspace", ResponseNamespace="thamsspace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out")]
        public bool deleteField([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xmlFileName, int did) {
            object[] results = this.Invoke("deleteField", new object[] {
                        xmlFileName,
                        did});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void deleteFieldAsync(string xmlFileName, int did) {
            this.deleteFieldAsync(xmlFileName, did, null);
        }
        
        /// <remarks/>
        public void deleteFieldAsync(string xmlFileName, int did, object userState) {
            if ((this.deleteFieldOperationCompleted == null)) {
                this.deleteFieldOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteFieldOperationCompleted);
            }
            this.InvokeAsync("deleteField", new object[] {
                        xmlFileName,
                        did}, this.deleteFieldOperationCompleted, userState);
        }
        
        private void OndeleteFieldOperationCompleted(object arg) {
            if ((this.deleteFieldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteFieldCompleted(this, new deleteFieldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="thamsspace", ResponseNamespace="thamsspace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getBMIDByADUserName([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("getBMIDByADUserName", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getBMIDByADUserNameAsync(string in0) {
            this.getBMIDByADUserNameAsync(in0, null);
        }
        
        /// <remarks/>
        public void getBMIDByADUserNameAsync(string in0, object userState) {
            if ((this.getBMIDByADUserNameOperationCompleted == null)) {
                this.getBMIDByADUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBMIDByADUserNameOperationCompleted);
            }
            this.InvokeAsync("getBMIDByADUserName", new object[] {
                        in0}, this.getBMIDByADUserNameOperationCompleted, userState);
        }
        
        private void OngetBMIDByADUserNameOperationCompleted(object arg) {
            if ((this.getBMIDByADUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBMIDByADUserNameCompleted(this, new getBMIDByADUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="thamsspace", ResponseNamespace="thamsspace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out")]
        public bool modifyField([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xmlFileName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fieldValues) {
            object[] results = this.Invoke("modifyField", new object[] {
                        xmlFileName,
                        fieldValues});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void modifyFieldAsync(string xmlFileName, string fieldValues) {
            this.modifyFieldAsync(xmlFileName, fieldValues, null);
        }
        
        /// <remarks/>
        public void modifyFieldAsync(string xmlFileName, string fieldValues, object userState) {
            if ((this.modifyFieldOperationCompleted == null)) {
                this.modifyFieldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmodifyFieldOperationCompleted);
            }
            this.InvokeAsync("modifyField", new object[] {
                        xmlFileName,
                        fieldValues}, this.modifyFieldOperationCompleted, userState);
        }
        
        private void OnmodifyFieldOperationCompleted(object arg) {
            if ((this.modifyFieldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.modifyFieldCompleted(this, new modifyFieldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="thamsspace", ResponseNamespace="thamsspace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out")]
        public int addField([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xmlFileName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fieldValues) {
            object[] results = this.Invoke("addField", new object[] {
                        xmlFileName,
                        fieldValues});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void addFieldAsync(string xmlFileName, string fieldValues) {
            this.addFieldAsync(xmlFileName, fieldValues, null);
        }
        
        /// <remarks/>
        public void addFieldAsync(string xmlFileName, string fieldValues, object userState) {
            if ((this.addFieldOperationCompleted == null)) {
                this.addFieldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddFieldOperationCompleted);
            }
            this.InvokeAsync("addField", new object[] {
                        xmlFileName,
                        fieldValues}, this.addFieldOperationCompleted, userState);
        }
        
        private void OnaddFieldOperationCompleted(object arg) {
            if ((this.addFieldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addFieldCompleted(this, new addFieldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void deleteFieldCompletedEventHandler(object sender, deleteFieldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteFieldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteFieldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getBMIDByADUserNameCompletedEventHandler(object sender, getBMIDByADUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBMIDByADUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBMIDByADUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void modifyFieldCompletedEventHandler(object sender, modifyFieldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class modifyFieldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal modifyFieldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void addFieldCompletedEventHandler(object sender, addFieldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addFieldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addFieldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591